### ISSUE TITLE
qeustion

### ISSUE THREAD

**Issue by migabyte** [art-class/v4#12]
any reason why geforce now hasnt been removed from apps.js ? tried it and am unable to login at all

**Comment by Asleep123** [comment]
Geforce has blocked access to their sites from proxies.

**Comment by migabyte** [comment]
oh ok

**Comment by proudparrot2** [comment]
> Geforce has blocked access to their sites from proxies.

They have? I just thought the login is really buggy
It works on later versions of ultraviolet which I’m looking into, but I haven’t gotten it working yet
I know Kazwire has
