### ISSUE TITLE
add every game from 3kh0 

### ISSUE THREAD

**Issue by UpTiGamer** [art-class/v4#16]
this site not have as many games as 3kh0 cool site why?

**Comment by migabyte** [comment]
cuz

**Comment by Asleep123** [comment]
that would be a huge pain, copy pasting each game. Also his games were hosted differently, he self hosted them,  and the server is now shut down because 3kh0 shut down.

**Comment by UpTiGamer** [comment]
> that would be a huge pain, copy pasting each game. Also his games were hosted differently, he self hosted them, and the server is now shut down because 3kh0 shut down.

he use githack tool?

**Comment by proudparrot2** [comment]
Yah I'm trying to only add ✨quality✨ games so it's not filled with junk games if you know what I mean

If you have any suggestions from there to add, I will gladly add them for you (or make a pull request)

**Comment by migabyte** [comment]
> Yah I'm trying to only add ✨quality✨ games so it's not filled with junk games if you know what I mean
> 
> If you have any suggestions from there to add, I will gladly add them for you (or make a pull request)

ok hear me out, newest version of cookie clicker. i cant find that shit anywhere

**Comment by proudparrot2** [comment]
alrighty, I'll look at it
