### ISSUE TITLE
hear me out guys

### ISSUE THREAD

**Issue by migabyte** [art-class/v4#17]
**Is your feature request related to a problem? Please describe.**
lack of aneurysm induced looking layout

**Describe the solution you'd like**
cruelty squad style theme

**Describe alternatives you've considered**
i havent considered anything else cuz im smarte

**Additional context**
search up cruelty squad menu and youll know, also i could make it if you want just tell me and i will make the theme and the pull request

**Comment by migabyte** [comment]
idk maybe i played cruelty squad too much but i like the menu

**Comment by proudparrot2** [comment]
is this like a theme or something or what
please be more descriptive

**Comment by migabyte** [comment]
its a theme that changes fonts and some bakcgrounds

**Comment by Asleep123** [comment]
i dont think we will be accepting themes that change fonts, you can do a pr though.

**Comment by migabyte** [comment]
ok <image src="https://thumbs.dreamstime.com/b/smiley-face-thumbs-up-14491322.jpg?w=20">
