### ISSUE TITLE
Doodle Jump isn't working

### ISSUE THREAD

**Issue by VillainsRule** [art-class/v4#23]
When you click on the Doodle Jump game, it redirects to an iFrame of the game image.
This is a result of the data file being incorrect. It currently reads:
```js
[{
        'id': 'doodlejump',
        'title': 'Doodle Jump',
        'url': 'https://upload.wikimedia.org/wikipedia/en/a/ac/Doodle_jump_icon.png',
        'image': 'https://assets-prd.ignimgs.com/2022/03/16/doodlejump-1647405974576.jpg'
}]
```

**Comment by proudparrot2** [comment]
Oh whoops - thanks for catching that
I'll fix it in a little bit, unless you want to open a pull request to fix it
