### ISSUE TITLE
Saying not connected to the internet 

### ISSUE THREAD

**Issue by ThatGirl2k** [art-class/v4#30]
Every time I go into the app and try to log into my Instagram (for example) it tells me to check my internet connection even through i am connected to the internet, and that goes for all the other apps i try to use (EX. Discord, telegram and TikTok)

![image](https://github.com/art-class/v4/assets/147771205/fe264d25-4cf6-4d87-a06e-57a720f19805)

 - Device: IPad 7th generation 
- Browser: Chrome and Safari

**Comment by ThatGirl2k** [comment]
![image](https://github.com/art-class/v4/assets/147771205/bf5672b6-0119-4397-aa8c-2402b14e13bd)

**Comment by proudparrot2** [comment]
That's interesting, let me try to test it

**Comment by ThatGirl2k** [comment]
Ok ty

**Comment by ThatGirl2k** [comment]
Is it fixed?

**Comment by Rahib777-7** [comment]
instagram blocks proxies

**Comment by proudparrot2** [comment]
My best guess is that either some API that instagram is using isn't being proxied correctly which can happen in some scenarios, or Instagram just straight up blocks proxies
