### ISSUE TITLE
Add Minecraft please

### ISSUE THREAD

**Issue by UpTiGamer** [art-class/v4#32]
### Game name

Minecraft

### Is this game on any other game websites?

https://eaglercraft.com/

**Comment by proudparrot2** [comment]
We could possibly get DMCA’d (our site gets taken down), but I’ll think about it

**Comment by Rahib777-7** [comment]
> We could possibly get DMCA’d (our site gets taken down), but I’ll think about it

that is pretty low but it is still a risk or they can use the proxy to load eagler proxied
![6A0C901F-2704-4D60-9FBE-203564632C09](https://github.com/art-class/v4/assets/74979271/aa2adda0-cefe-41b0-9322-2098287483cd)

**Comment by proudparrot2** [comment]
what did you do

**Comment by Asleep123** [comment]
to the font

**Comment by Rahib777-7** [comment]
> to the font

the font looks nice doesn't it
