### ISSUE TITLE
bookmarklet edition

### ISSUE THREAD

**Issue by HAlThO** [art-class/v4#33]
Thank you for your very good site.
https://artclass.site has been banned.
Could you please create a bookmarklet that opens artclass with about:blank?
Sorry for my bad English.

**Comment by proudparrot2** [comment]
What filter(s) do you have?

**Comment by HAlThO** [comment]
I live in Japan and they use a Japanese filter called LoiLo Web Filter, which only blocks certain URLs.

**Comment by migabyte** [comment]
just asking but did you try obiyvutfydrtefyguhi.artclass.site ? basically just putting somehting random, then .artclass.site
you probably have though

**Comment by Rahib777-7** [comment]
> I live in Japan and they use a Japanese filter called LoiLo Web Filter, which only blocks certain URLs. This filter does not prohibit inframes.

chromebooks or computer (if computer what windows/macos)

**Comment by HAlThO** [comment]
> > 私は日本に住んでいますが、特定の URL のみをブロックする LoiLo Web フィルターという日本のフィルターを使用しています。このフィルタはインフレームを禁止しません。
> 
> Chromebook またはコンピューター (コンピューターの場合は Windows/MacOS)

chrome book

**Comment by HAlThO** [comment]
> ちょっと聞いたんですが、obiyvutfydrtefyguhi.artclass.site は試しましたか？基本的にはランダムに何かを置くだけですが、 おそらくあなたが持っている.artclass.site

It was impossible because artclass.site itself is prohibited.

**Comment by Rahib777-7** [comment]
> > ちょっと聞いたんですが、obiyvutfydrtefyguhi.artclass.site は試しましたか？基本的にはランダムに何かを置くだけですが、 おそらくあなたが持っている.artclass.site
> 
> It was impossible because artclass.site itself is prohibited.

habibi join the discord and ask "where do you get free links pakistani shia twelver"

**Comment by Rahib777-7** [comment]
> > ちょっと聞いたんですが、obiyvutfydrtefyguhi.artclass.site は試しましたか？基本的にはランダムに何かを置くだけですが、 おそらくあなたが持っている.artclass.site
> 
> It was impossible because artclass.site itself is prohibited.

@proudparrot2 can i leak some links then if that was deleted

**Comment by Asleep123** [comment]
no dont

**Comment by Rahib777-7** [comment]
> no dont

plzzzzz

**Comment by proudparrot2** [comment]
> > > ちょっと聞いたんですが、obiyvutfydrtefyguhi.artclass.site は試しましたか？基本的にはランダムに何かを置くだけですが、 おそらくあなたが持っている.artclass.site
> > 
> > 
> > It was impossible because artclass.site itself is prohibited.
> 
> @proudparrot2 can i leak some links then if that was deleted

no???????????????
