### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by PizzaGod873** [art-class/v4#36]
### What's happening?

The screen is just white.

### Please give instructions on how we can reproduce the error you're reporting.

Just go to any game/app

### Please describe what's supposed to happen

Show what it normally does

### Anything else we should know?

Some javascript commands are blocked, and it works on other models of chromebook.

**Comment by Rahib777-7** [comment]
screenshit

**Comment by Rahib777-7** [comment]
if you are referring to this
![image](https://github.com/art-class/v4/assets/74979271/812a8ce0-c7d6-4236-b427-ff6927cc510e)
reload the page

**Comment by proudparrot2** [comment]
> if you are referring to this ![image](https://user-images.githubusercontent.com/74979271/282335137-812a8ce0-c7d6-4236-b427-ff6927cc510e.png) reload the page

no he's referring to when the proxy just breaks most likely due to bad wifi

**Comment by Rahib777-7** [comment]
> > if you are referring to this ![image](https://user-images.githubusercontent.com/74979271/282335137-812a8ce0-c7d6-4236-b427-ff6927cc510e.png) reload the page
> 
> no he's referring to when the proxy just breaks most likely due to bad wifi

oh @PizzaGod873 are you using any extensions if you are list them and say what browser you are using
