### ISSUE TITLE
Actual White Screen

### ISSUE THREAD

**Issue by The-Rock-21** [art-class/v4#38]
### What's happening?

The code for site no work

### Please give instructions on how we can reproduce the error you're reporting.

I click on website. Just white screen with a couple of links
![Screenshot 2023-11-13 7 24 08 AM](https://github.com/art-class/v4/assets/101891804/fe554993-e54d-4626-bcb8-38c0e4ad29d9)

### Please describe what's supposed to happen

Its supposed to show the site normally

**Comment by sarahernandez12** [comment]
its doing the same to mine

**Comment by justinistheone** [comment]
same

**Comment by justinistheone** [comment]
but it work for my friend yoooo

**Comment by justinistheone** [comment]
why not work for us

**Comment by The-Rock-21** [comment]
Oh ok. I just tried it now. It works
