### ISSUE TITLE
none of the games are loading in 

### ISSUE THREAD

**Issue by thefirstnoob98** [art-class/v4#39]
### What's happening?

the games wont load in 

### Please give instructions on how we can reproduce the error you're reporting.

i don't know how your supposed to but it cant get the game to fetch and load saying its a internal server error

### Please describe what's supposed to happen

the game is supposed to load

**Comment by thefirstnoob98** [comment]
apps are loaded but games wont load 
![Screenshot 2023-11-15 8 23 18 AM](https://github.com/art-class/v4/assets/150808983/7f28e65f-0cc8-4c61-8fbf-6a9e20472393)

**Comment by Asleep123** [comment]
Deleted your comment because it contained a link.
