### ISSUE TITLE
Telegram image is broken

### ISSUE THREAD

**Issue by VillainsRule** [art-class/v4#44]
### What's happening?

Telegram image is broken

### Please give instructions on how we can reproduce the error you're reporting.

Go to the apps page and observe with eyes

### Please describe what's supposed to happen

The image loads

### Anything else we should know?

annotate >>

**Comment by proudparrot2** [comment]
open pr

**Comment by proudparrot2** [comment]
its an image its not that deep

**Comment by thewilloftheshadow** [comment]
Obviously you do
