### ISSUE TITLE
Error processing your request 

### ISSUE THREAD

**Issue by hihihi1111** [art-class/v4#47]
### What's happening?

The screen goes to error processing your request every time i try to play a game

### Please describe what's supposed to happen

It's supposed to pull up the game i want to play

### Anything else we should know?

I'm on a chromebook

**Comment by proudparrot2** [comment]
@hihihi1111 we've been testing some things out with that domain so stuff might not work fully, sorry

**Comment by Asleep123** [comment]
also some content was removed from your message for containing an art class link, please be more careful next time! but yes as parrot said above we’re kinda testing some new stuff out with that domain and it might not work 100% just yet

**Comment by hihihi1111** [comment]
Ok, thank you!
