### ISSUE TITLE
just a suggestion

### ISSUE THREAD

**Issue by migabyte** [art-class/v4#5]
hi, small suggestion that doesnt make really any difference but in the apps section instead of using sflix i reccomend http://movie-web.app/ because it doesnt have popups and i feel the design is better

**Comment by proudparrot2** [comment]
I’ll add it also, thanks
If you want to make a pull req, you can

**Comment by migabyte** [comment]
ok sure  <image src="https://cdn.vectorstock.com/i/1000x1000/53/95/thumb-up-emoticon-vector-1075395.webp"></image>
