### ISSUE TITLE
Where's the uv.bundle.js file??

### ISSUE THREAD

**Issue by Kenfin777** [art-class/v4#56]
### What's happening?

Missing File

### Please give instructions on how we can reproduce the error you're reporting.

In the html files, each one mentions a file called "uv.bundle.js". It didn't show up in my files when I downloaded it.

### Please describe what's supposed to happen

I'm supposed to get the "uv.bundle.js" file

### Anything else we should know?

_Yes_

**Comment by proudparrot2** [comment]
uv.bundle.js (and client, handler, and sw) are served by express. Are you attempting to run this statically? Art Class needs to be ran with the index.js file in the root. It is not a static application.

**Comment by Kenfin777** [comment]
> uv.bundle.js (and client, handler, and sw) are served by express. Are you attempting to run this statically? Art Class needs to be ran with the index.js file in the root. It is not a static application.

well, I am trying to just use it by opening the html files

**Comment by Kenfin777** [comment]
If I ran it in [glitch](glitch.com), it suspends my project for violating the tos. In replit, when I run it it doesn't work.

**Comment by Kenfin777** [comment]
###this is the index.html  `<!DOCTYPE html>
<html>
  <head>
    <link
      rel="shortcut icon"
      href="./assets/images/icon.png"
      type="image/png"
    />
    <title>Art Class</title>

    <link rel="stylesheet" href="./css/master.css" />

    <script src="/uv/uv.bundle.js" charset="UTF-8"></script>
    <script src="/uv/uv.config.js"></script>
    <script src="./js/preload.js"></script>
  </head>

  <body theme="main">
    <nav>
      <div class="logo">
        <img src="./assets/images/icon.png" alt="Logo" draggable="false" />
        <h1>Art Class</h1>
      </div>

      <p id="time"></p>

      <div class="navitems">
        <div class="navitem"><a selected href="/">Home</a></div>
        <div class="navitem"><a href="/gs.html">Games</a></div>
        <div class="navitem"><a href="/apps.html">Apps</a></div>
        <div class="navitem"><a href="/emulator.html">Emulator</a></div>
        <div class="navitem"><a href="/search.html">Search</a></div>
      </div>
    </nav>

    <div class="center-container">
      <h1>Welcome to <span>Art Class</span></h1>
      <p id="splash"></p>
      <br />
      <button
        onclick="window.location.href='/search.html?q=https://discord.gg/tMaHQ2dyk5'"
        class="button play"
      >
        Join our Discord
      </button>
      <button onclick="launchab()" id="launchab" class="button play">
        Launch in about:blank
      </button>
    </div>

    <div class="links">
      <div class="left">
        <a href="https://github.com/art-class/v4">GitHub</a>
        <a href="https://discord.gg/tMaHQ2dyk5">Discord</a>
      </div>

      <div class="right">
        <a href="./settings.html">Settings</a>
        <a href="./about.html">About</a>
      </div>
    </div>
  </body>

  <script>
    fetch('./assets/data/splash.json')
      .then((res) => res.json())
      .then((data) => {
        document.querySelector('#splash').innerHTML =
          data[Math.floor(Math.random() * data.length)]
      })
  </script>

  <script src="./js/index.js"></script>
</html>
`

**Comment by Kenfin777** [comment]
![image](https://github.com/art-class/v4/assets/153947091/4d0d6a7f-5cf2-4121-9736-fdad77d80e24)

**Comment by Kenfin777** [comment]
![Screenshot 2024-02-14 12 26 15 PM](https://github.com/art-class/v4/assets/153947091/2fee546a-fd2e-44b5-9776-814068eb00c5)

My gmail if u need to contact me: [gmail](potatodude12345678999@gmail.com)

**Comment by proudparrot2** [comment]
> > uv.bundle.js (and client, handler, and sw) are served by express. Are you attempting to run this statically? Art Class needs to be ran with the index.js file in the root. It is not a static application.
> 
> well, I am trying to just use it by opening the html files

Well that doesn’t work

**Comment by IncognitoTGT** [comment]
lmao you need https for service workers
