### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by MrBanana-Brains** [art-class/v4#60]
### What's happening?

Uploading to Glitch causes it to be taken down

### Please give instructions on how we can reproduce the error you're reporting.

Log into glitch and press new project. Import from github. Then it will be taken down.

### Please describe what's supposed to happen

.

**Comment by proudparrot2** [comment]
This is, although unfortunate, working as intended because Glitch doesn't allow proxies on their platform

**Comment by MrBanana-Brains** [comment]
Thanks just wanna let u know because its in your read me.
