### ISSUE TITLE
koyeb

### ISSUE THREAD

**Issue by nikhil28303** [art-class/v4#75]
### What's happening?

when I deploy artclass v4 to koyeb it says that I am shady and when I try anything else it is blocked by goguardian or ek-express or the school wifi

### Please give instructions on how we can reproduce the error you're reporting.

go to a school chromebook and get on a katyisd chromebook and click koyeb which says when I deploy it say " you might be violating our terms of service and basically saying I am shady. could you send me a link for artclass v4 unblocked for katyisd school Chromebook in which it works?make in unblocked by goguardian and ek-express and school wifi.

### Please describe what's supposed to happen

I think it should open up artclass website but it is blocked and koyeb not working.

**Comment by Asleep123** [comment]
Koyeb links may be blocked by your school. We can’t do anything about that.
Also, a lot of popular hosting platforms are banning proxies, because they are used so often to host them. We can’t help at all with this issue, it’s entirely not in our hands.
