### ISSUE TITLE
Wheres Env file and how to add own proxy?

### ISSUE THREAD

**Issue by Veslydev** [art-class/v4#77]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Nothing title explains

**Comment by Asleep123** [comment]
there is no env file, what do you mean how to add own proxy? there’s self host instructions in the readme.

**Comment by Veslydev** [comment]
let port = parseInt(process.env.PORT || ""); on index.js https://github.com/art-class/v4/blob/2e932220c528fa33cb3d619553a2121fbb93a541/index.js#L41 | Add own proxy by like adding private proxys for artclass selfhost and make lattency good etc.

**Comment by Asleep123** [comment]
you can either create a `.env` file with `PORT="3000"` or just adjust the default port after the `|`
if you self host it, you’re hosting everything, including the proxy, nothing is hosted by us.
